# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-08 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20180108_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sizw',
            new_name='size',
        ),
    ]
